services:
  - type: web
    name: flask-note-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn website:create_app()
    envVars:
      - key: DATABASE_URL
        sync: false 